#!/usr/bin/env python3

from selenium import webdriver
from datetime import datetime
import requests
import getpass
import time
import os, sys
import re

VERSION = '0.0.1'
THIS_YEAR = datetime.today().year

def extract_auth_token(text):
    index = text.find("authenticity_token")
    if index:
        return text[index:index+512].split('"')[2]


def canvas_login(url, username, password):
    
    session = requests.session()
    login_url = url + "/login/ldap"

    data = {
        "utf8": '✓',
        "authenticity_token": None,
        "redirect_to_ssl": '1',
        "pseudonym_session[unique_id]": username,
        "pseudonym_session[password]": password,
        "pseudonym_session[remember_me]": '0'
    }

    with session.get(login_url) as response:
        if response.status_code == 200:
            data["authenticity_token"] = extract_auth_token(response.text)

    if data["authenticity_token"]:
        with session.post(login_url, data=data) as response:
            if response.status_code == 200:
                return session

    return None


def enum_courses(url, session):

    courses = dict()
    
    with session.get(url + "/courses/") as response:
        if response.status_code == 200:
            links = re.findall('"/courses/.*" title=.*', response.text)
            for link in links:
                courses[link.split('"')[1].split('/')[2]] = link.split('"')[3]
    
    return courses


def load_driver_cookies(url, session):
    
    options = webdriver.ChromeOptions()
    options.headless = True
    
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    driver.delete_all_cookies()

    cookies = [cookie.__dict__ for cookie in session.cookies]

    for cookie in cookies:
        new_cookie = dict()
        for key in cookie:
            new_cookie[key] = cookie[key]
            if key == "_rest":
                for subkey in cookie[key]:
                    new_cookie[key] = cookie[key]
        driver.add_cookie(new_cookie)

    return driver


def load_course(url, course, driver):

    assignments = dict()
    assignments_url = url + "/courses/" + course + "/assignments/"

    driver.get(assignments_url)
    time.sleep(2)
    lines = driver.page_source.split('\n')
    for i, line in enumerate(lines):
        if '<a href="' + assignments_url in line: 
            a_id = line.split('/')[6].split('"')[0]
            name = lines[i + 1].strip()
            for j in range(i, len(lines)):
                if "Due" in lines[j]:
                    if ':' in lines[j+2]:
                        fmt = "%b %d at %I:%M%p%Y"
                    else:
                        fmt = "%b %d at %I%p%Y"
                    
                    due = datetime.strptime(lines[j+2].strip() + str(THIS_YEAR), fmt)
                    break

            assignments[a_id] = (name, due)

    return assignments


if __name__ == "__main__":

    if "-h" in sys.argv or "--help" in sys.argv or len(sys.argv) == 1:
        print("canvas-cli:")
        print("    --username / -u    Canvas username (required)")
        print("      --domain / -d    Canvas subdomain (required)")
        print("        --help / -h    Prints this page")
        print("         --all / -a    Shows past assignments", end="\n\n")
        print("example: %s -u student01 -d unt" % sys.argv[0])
        exit(0)
   
    base_domain = "https://%s.instructure.com"
    username = ''
    password = ''
    domain = ''

    for i, token in enumerate(sys.argv):
        if token == "-d" or token == "--domain":
            if i + 1 < len(sys.argv) or sys.argv[i + 1][0] != '-':
                domain = sys.argv[i + 1]
            else:
                print("missing domain (ex: <this part>.instructure.com)")
                exit(0)
        if token == "-u" or token == "--username":
            if i + 1 < len(sys.argv) or sys.argv[i + 1][0] != '-':
                username = sys.argv[i + 1]
            else:
                print("missing username")
                exit(0)

    password = getpass.getpass("Canvas password: ")

    if not domain or not username or not password:
        print("missing an argument")
        exit(0)

    url = base_domain % domain

    print("[>] logging in...")
    session = canvas_login(url, username, password)
   
    if not session:
        print("[x] failed to log in")
        exit(0)

    print("[>] getting course info...")
    courses = enum_courses(url, session)
    print("[>] loading web driver...")
    driver = load_driver_cookies(url, session)

    print("[>] dumping courses...")
    for course in courses:
        print(courses[course])
        assignments = load_course(url, course, driver)
        for assignment in sorted(assignments, key=lambda x: assignments[x][1].timestamp()):
            title, due = assignments[assignment]
            if due.timestamp() > datetime.today().timestamp():
                print('  ', title, '[%s]' % assignment)
                print('    DUE: ', due)
            elif "-a" in sys.argv or "--all" in sys.argv:
                print('  ', title, 'id:', assignment)
                print('    DUE: ', due)
