#!/usr/bin/env python3

from selenium import webdriver
from datetime import datetime
import requests
import getpass
import string
import time
import os, sys
import re

PASS="[\033[1;32m+\033[0m]"
PROG="[\033[1;34m>\033[0m]"
FAIL="[\033[1;31mx\033[0m]"

VERSION = '0.0.2'
THIS_YEAR = datetime.today().year

def extract_auth_token(text):
    index = text.find("authenticity_token")
    if index:
        return text[index:index+512].split('"')[2]


def canvas_login(url, username, password):
    
    session = requests.session()
    login_url = url + "/login/ldap"

    data = {
        "utf8": '✓',
        "authenticity_token": None,
        "redirect_to_ssl": '1',
        "pseudonym_session[unique_id]": username,
        "pseudonym_session[password]": password,
        "pseudonym_session[remember_me]": '0'
    }

    with session.get(login_url) as response:
        if response.status_code == 200:
            data["authenticity_token"] = extract_auth_token(response.text)

    if data["authenticity_token"]:
        with session.post(login_url, data=data) as response:
            if response.status_code == 200:
                return session

    return None


def enum_courses(url, session):

    courses = dict()
    
    with session.get(url + "/courses/") as response:
        if response.status_code == 200:
            links = re.findall('"/courses/.*" title=.*', response.text)
            for link in links:
                courses[link.split('"')[1].split('/')[2]] = link.split('"')[3]
    
    return courses


def load_driver_cookies(url, session):
    
    options = webdriver.ChromeOptions()
    options.headless = True
    
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    driver.delete_all_cookies()

    cookies = [cookie.__dict__ for cookie in session.cookies]

    for cookie in cookies:
        new_cookie = dict()
        for key in cookie:
            new_cookie[key] = cookie[key]
            if key == "_rest":
                for subkey in cookie[key]:
                    new_cookie[key] = cookie[key]
        driver.add_cookie(new_cookie)

    return driver


def load_course(url, course, driver):

    assignments = dict()
    assignments_url = url + "/courses/" + course + "/assignments/"

    driver.get(assignments_url)
    time.sleep(2.5)
    lines = driver.page_source.split('\n')
    for i, line in enumerate(lines):
        if '<a href="' + assignments_url in line: 
            a_id = line.split('/')[6].split('"')[0]
            name = lines[i + 1].strip()
            for j in range(i, len(lines)):
                if "Due" in lines[j]:
                    if ':' in lines[j+2]:
                        fmt = "%b %d at %I:%M%p%Y"
                    else:
                        fmt = "%b %d at %I%p%Y"
                    
                    due = datetime.strptime(lines[j+2].strip() + str(THIS_YEAR), fmt)
                    break

            assignments[a_id] = (name, due)

    return assignments


def assignment_info(url, course_id, assignment_id, driver):
    
    driver.get(url + "/courses/" + course_id + "/assignments/" + assignment_id)
    time.sleep(5)
    lines = driver.page_source.split('\n')

    assignment = {
        "title": '',
        "description": '',
        "downloads": list()
    }

    for i, line in enumerate(lines):
        if "title-content" in line:
            assignment["title"] = lines[i+2].strip()
        if "description user_content" in line:
            if len(line.split('<p>')):
                for part in line.split('<p>')[1:]:
                    if "instructure_file_holder" not in part:
                        assignment["description"] += part.split('</p>')[0]
        if "instructure_file_holder" in line:
            index = line.find("href")
            link = line[index:].split('"')[1]
            download = url + link.split('?')[0] + "/download?download_frd=1"
            assignment["downloads"].append(download)

    return assignment

if __name__ == "__main__":

    if "-h" in sys.argv or "--help" in sys.argv or len(sys.argv) == 1:
        print("canvas-cli:")
        print("    --username / -u    Canvas username (required)")
        print("      --domain / -d    Canvas subdomain (required)")
        print("        --help / -h    Prints this page")
        print("         --all / -a    Shows past assignments", end="\n\n")
        print("example: %s -u student01 -d unt" % sys.argv[0])
        exit(0)
   
    if "-v" in sys.argv:
        print("Canvas Cli -", VERSION)
        exit(0)

    base_domain = "https://%s.instructure.com"
    username = ''
    password = ''
    domain = ''

    for i, token in enumerate(sys.argv):
        if token == "-d" or token == "--domain":
            if i + 1 < len(sys.argv) or sys.argv[i + 1][0] != '-':
                domain = sys.argv[i + 1]
            else:
                print("missing domain (ex: <this part>.instructure.com)")
                exit(0)
        if token == "-u" or token == "--username":
            if i + 1 < len(sys.argv) or sys.argv[i + 1][0] != '-':
                username = sys.argv[i + 1]
            else:
                print("missing username")
                exit(0)

    password = getpass.getpass("Canvas password: ")

    if not domain or not username or not password:
        print("missing an argument")
        exit(0)

    url = base_domain % domain

    print(PROG, "logging in...")
    session = canvas_login(url, username, password)
   
    if not session:
        print(FAIL, "failed to log in")
        exit(0)

    print(PASS, "getting course info...")
    courses = enum_courses(url, session)
    print(PROG, "loading web driver...")
    driver = load_driver_cookies(url, session)

    index = 1
    options = list()

    print(PASS, "dumping courses...")
    for course in courses:
        print("\033[1;32m", courses[course], "\033[0m", sep='')
        assignments = load_course(url, course, driver)
        if len(assignments) == 0:
            print("    \033[1;31mno assignments\033[0m")
        for assignment in sorted(assignments, key=lambda x: assignments[x][1].timestamp()):
            title, due = assignments[assignment]
            today = datetime.today()
            if due.timestamp() > today.timestamp() or "-a" in sys.argv or "--all" in sys.argv:
                until = due.timetuple().tm_yday - today.timetuple().tm_yday
                if until == 0:
                    until = "\033[1;31mdue today!\033[0m"
                else:
                    until = '(\033[1;34m%s\033[m) days left' % until if until != 1 else '(\033[1;31m%s\033[0m) day left!' % until
                print('[\033[1;35m%d\033[0m]  \033[1;33m' % index, title, '\033[0m[%s]' % assignment)
                print('      DUE: %s, %s' % (due.strftime("\033[1;32m%m/%d\033[0m at %I:%M%p"), until))
                options.append((course, assignment))
                index += 1
   
    i = input("select an assignment by number [1->%d] or type 'q' to quit: " % (index - 1))
    deny = ''.join([ch for ch in set(string.printable) - set(string.digits)])

    for ch in deny:
        if i == ch:
            exit(0)
    if i != '0':
        course, assignment = options[int(i) - 1]
        
        info = assignment_info(url, course, assignment, driver)
        print("Title:", info["title"])
        print("Description:", info["description"])
        
        if len(info["downloads"]):
            choice = input("would you like to download the files? [y/n]: ")
            if choice.lower() == 'y':
                for link in info["downloads"]:
                    print("downloading from link %s..." % link)
                    driver.get(link)
